"""Add task_dependencies table

Revision ID: 400c6b1543ee
Revises: fa2f8e30ad71
Create Date: 2025-07-09 08:58:51.306939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400c6b1543ee'
down_revision = 'fa2f8e30ad71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependencies',
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['task.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_dependencies')
    # ### end Alembic commands ###
