"""add_title_to_notification

Revision ID: 9603bed3fcbf
Revises: add_show_at_to_notification
Create Date: 2025-07-12 14:29:26.195222

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9603bed3fcbf"
down_revision = "add_show_at_to_notification"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("title", sa.String(length=100), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notification", schema=None) as batch_op:
        batch_op.drop_column("title")

    # ### end Alembic commands ###
