name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov


      - name: Create .env from GitHub secret
        run: echo "$BACKEND_ENV_FILE" > .env
        working-directory: ./backend
        env:
          BACKEND_ENV_FILE: ${{ secrets.BACKEND_ENV_FILE }}

      - name: Run tests with coverage (xml and text)
        run: |
          pytest --cov --cov-report=term-missing --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          flags: backend
          name: backend-coverage
          fail_ci_if_error: false

      - name: Generate markdown coverage summary
        if: github.event_name == 'pull_request'
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: file
          fail_below_min: false

      - name: Make coverage summary writable
        if: github.event_name == 'pull_request'
        run: chmod +w code-coverage-results.md

      - name: Prepend header to coverage summary
        if: github.event_name == 'pull_request'
        run: |
          echo -e "# Backend Coverage\n\n$(cat code-coverage-results.md)" > code-coverage-results.md

      - name: Prepend header to coverage summary
        if: github.event_name == 'pull_request'
        run: |
          echo -e "# Backend Coverage\n\n$(cat code-coverage-results.md)" > code-coverage-results.md

      - name: Post coverage summary as PR comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: code-coverage-results.md
          header: Backend Coverage

      - name: DeepSource Test Coverage
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: python
          coverage-file: coverage.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
