name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements.txt
          pip install pytest pytest-cov

      - name: Copy .env to backend
        run: cp ../.env .env
        working-directory: ./backend

      - name: Run tests with coverage (xml and text)
        run: |
          pytest --cov --cov-report=term-missing --cov-report=xml > coverage.txt

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./backend/coverage.txt
          flags: backend
          name: backend-coverage
          fail_ci_if_error: false

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ./backend/coverage.txt
          header: Backend Coverage
          hide_and_recreate: true
